"""Initial migration

Revision ID: 0b3bf27b1b0f
Revises: 
Create Date: 2026-08-29 01:57:12.556583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3bf27b1b0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medecins', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('patients', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('role', sa.String(length=20), nullable=True))
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('patients', 'role')
    op.drop_column('patients', 'hashed_password')
    op.alter_column('medecins', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
