"""Add disponibilites and consultation notes

Revision ID: c99d9f4f18a4
Revises: 8a300157d57f
Create Date: 2026-08-29 02:54:12.572345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99d9f4f18a4'
down_revision: Union[str, Sequence[str], None] = '8a300157d57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
